// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByQup-gZRM7XvJXGJE2_dy2raY-TO3LGY',
    appId: '1:636779565719:android:717c00b6be6bef6c90cfd2',
    messagingSenderId: '636779565719',
    projectId: 'bitrise-test-28b89',
    storageBucket: 'bitrise-test-28b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvn2Kv6g453Rchtq2595YYkwqtjQrrt3Q',
    appId: '1:636779565719:ios:c6ec306b7bdc49d190cfd2',
    messagingSenderId: '636779565719',
    projectId: 'bitrise-test-28b89',
    storageBucket: 'bitrise-test-28b89.appspot.com',
    iosClientId: '636779565719-a7dniaepbevd009orenrqapq0jipuu6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitrisetest',
  );
}
